name: UltimateBackpack
main: com.minkang.ultimate.backpack.BackpackPlugin
version: 1.3.0
api-version: 1.16
author: Mingang Jeon & Team
commands:
  가방:
    description: 개인 가방 명령어
    aliases: [backpack, bag, 백팩]
permissions:
  ultimatebackpack.admin:
    description: 운영자 권한(지급/크기/리로드/설정)
    default: op
