name: PixelTicket
main: gg.pixelticket.PixelTicketPlugin
version: 1.2.1
api-version: 1.16
commands:
  지급:
    description: 권 지급/설정/테스트
    usage: "/지급 <권종류> <플레이어> <갯수> | /지급 설정 <권종류> | /지급 테스트"
  하트비늘:
    description: 하트비늘 관리/취소/지급
    usage: "/하트비늘 [취소|아이템|지급 <플레이어> <개수>|리로드]"
permissions:
  pixelticket.admin:
    default: op
