name: PixelTicket
main: gg.pixelticket.PixelTicketPlugin
version: 1.0.6
api-version: 1.16
commands:
  지급:
    description: 권 지급/설정/테스트
    usage: "/지급 <권종류> <플레이어> <갯수> | /지급 설정 <권종류> | /지급 테스트"
permissions:
  pixelticket.admin:
    default: op
