name: PocketPhoto
main: com.minkang.ultimate.pocketphoto.Main
version: 1.2.4
api-version: 1.16
commands:
  "포켓사진":
    description: 파티 슬롯(1~6)의 픽셀몬을 사진 아이템으로 변환
    usage: "/포켓사진 <1~6>"
    aliases: [pokepic, picmon]
    permission: ""
    permission-message: ""
