name: PixelTicket
main: gg.pixelticket.PixelTicketPlugin
version: 1.0.3
api-version: 1.16
author: yourteam
commands:
  지급:
    description: 권 지급 및 설정
    usage: /지급 <권종류> <플레이어> <갯수> | /지급 설정 <권종류>
    permission: pixelticket.admin
permissions:
  pixelticket.admin:
    default: op
