name: Build PixelTicket
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }
  workflow_dispatch:
jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
      - name: Build (Maven)
        run: mvn -B -ntp -DskipTests package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PixelTicket-jar
          path: target/PixelTicket-1.0.1.jar
          if-no-files-found: error
